### ISSUE TITLE
Server sort order not retained

### ISSUE THREAD

**Issue by coffenbacher** [TheGnarCo/redux-entity-config#17]
I think by throwing away the `result` field here, we're losing the sort order of the response. Since we can do arbitrarily complicated sorting on the server before returning the results, that's important information.

https://github.com/TheGnarCo/redux-entity-config/blob/0a9cfb2f9d90eb3df4f38e3c60df84af3f7d9eda/src/base_config.js#L122

and Dan Abramov's explanation of sorting with `normalizr`:
https://github.com/paularmstrong/normalizr/issues/9

**Comment by mikestone14** [comment]
closed by #18
